name: app

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          debug: true
          script: |
            sudo rm -rf fab-sber-test
            git clone ${{ secrets.CLONE_ADDRESS }}
            cd fab-sber-test
            
            touch auth_app/.env
            echo GH_CLIENT_ID=${{ secrets.GH_CLIENT_ID }} >> auth_app/.env
            echo GH_CLIENT_SECRET=${{ secrets.GH_CLIENT_SECRET }} >> auth_app/.env
            echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> auth_app/.env

            sudo docker-compose stop
            sudo docker-compose build app
            sudo docker-compose up -d

#  send_message:
#    runs-on: ubuntu-latest
#    needs: deploy
#    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
#    steps:
#    - name: send message
#      uses: appleboy/telegram-action@master
#      with:
#        to: ${{ secrets.TELEGRAM_TO }}
#        token: ${{ secrets.TELEGRAM_TOKEN }}
#        message: ${{ github.workflow }} успешно выполнен!
